[package]
name = "parallel-ising-tm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = { ver = "0.15.6", features = ["rayon"]}
num = "0.4.0"
